apiVersion: v1
kind: Pod
metadata:
  name: privileged-pod
spec:
  containers:
  - name: debug
    image: ubuntu
    securityContext:
      privileged: true
    command:
      - "sleep"
      - "infinity"
    volumeMounts:
    - mountPath: /host
      name: host-volume
  volumes:
  - name: host-volume
    hostPath:
      path: /
      type: Directory
  nodeSelector:
    kubernetes.io/hostname: your-node-name
