apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-prvt-cluster
  region: us-east-1

vpc:
  id: "vpc-07b96abff8bd28cdb"
  cidr: "10.0.0.0/16"
  subnets:
    private:
      us-east-1b: { id: subnet-0d4b766429002909b }
      us-east-1a: { id: subnet-0cd82458f5143c84d }
  clusterEndpoints:
    publicAccess:  true
    privateAccess: true    

managedNodeGroups:
  - name: ng-raju
    instanceType: t3.medium
    labels: { role: builders }
    minSize: 2
    maxSize: 3
    spot: true
    ssh: 
      allow: true
      publicKeyName: python-test
    subnets:
      - subnet-0d4b766429002909b
      - subnet-0cd82458f5143c84d
    privateNetworking: true     
    tags:
      Name: ng-raju
