apiVersion: v1
items:
- apiVersion: policy/v1
  kind: PodDisruptionBudget
  metadata:
    creationTimestamp: "2024-07-02T11:01:37Z"
    generation: 1
    labels:
      eks.amazonaws.com/component: coredns
      k8s-app: kube-dns
    name: coredns
    namespace: kube-system
    resourceVersion: "39883"
    uid: 18b4cdea-d7a0-4e38-8fd7-481fec38c9ea
  spec:
    maxUnavailable: 1
    selector:
      matchLabels:
        eks.amazonaws.com/component: coredns
        k8s-app: kube-dns
  status:
    conditions:
    - lastTransitionTime: "2024-07-02T15:06:54Z"
      message: ""
      observedGeneration: 1
      reason: InsufficientPods
      status: "False"
      type: DisruptionAllowed
    currentHealthy: 1
    desiredHealthy: 1
    disruptionsAllowed: 0
    expectedPods: 2
    observedGeneration: 1
kind: List
metadata:
  resourceVersion: ""
